### PR TITLE
Proposed improvements (Mindera)

### PR DESCRIPTION
**Pull request by aaagoncalojoaoc**

### CODE REVIEW

**Review by PedroQuinta — COMMENTED** [review]
Thank you for the proposed improvements. Could I ask you what is most common practice, is it to make the changes in the pull request directly and then merge or to change the original files and make another commit?

**Comment by aaagoncalojoaoc** [comment]
In this case it's probably better if you commit to your original repo instead of my fork 🙂

**Comment by PedroQuinta** [comment]
I am going to commit two more attempts at the challenge with the proposed improvements tackled. In both cases I had trouble with the ScrollView and OnClick. In both versions they are not working. I do not know why as I searched and searched and try to fix it but in the end I couldn't and was left always with an D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN errors. 
Even if I am not selected I would be delighted if you could point me in the right direction to solve this problem.

**Comment by PedroQuinta** [comment]
I have commited my second attempt which is the full version without the scrollview and clicking working. I tried but couldn't implemented it in time. And the third attempt was my try at making all my layouts with recycler view in order to make them more dynamically but again i was confronted with the scroll view and button click barrier.

**Comment by aaagoncalojoaoc** [comment]
@PedroQuinta I'm afraid I can't compile the second and third attempts, as I can't find any `.gradle` files for them. Can you provide documentation on how to build these two version of the app from the source code?

**Comment by PedroQuinta** [comment]
I begin by apologizing. In fact I do have some knowledge in git, at least the basic concepts and its workarounds however I have never really had the chance to practice it intensively and professionally hence these mistakes. My intention was to commit the whole project, gradle files included, still I will provide documentation on how to proceed to import these projects from just the source code. Should I provide the steps here?

**Comment by PedroQuinta** [comment]
Sorry for the inconvenience but in my attempt to further my practice with git, after several tries, I got rid of both the previous third and second attempt and managed to commit a project named Second Attempt with the necessary gradle files.

**Pull request closed without merging**
